require 'sinatra/activerecord'
require './models'

require 'pry'; binding.pry;
Book.create(title: "ULYSSES")
Book.create(title: "THE GREAT GATSBY")
Book.create(title: "A PORTRAIT OF THE ARTIST AS A YOUNG MAN")
Book.create(title: "LOLITA")
Book.create(title: "BRAVE NEW WORLD")
Book.create(title: "THE SOUND AND THE FURY")
Book.create(title: "CATCH-22")
Book.create(title: "DARKNESS AT NOON")
Book.create(title: "SONS AND LOVERS")
Book.create(title: "THE GRAPES OF WRATH")
Book.create(title: "UNDER THE VOLCANO")
Book.create(title: "THE WAY OF ALL FLESH")
Book.create(title: "1984")
Book.create(title: "I, CLAUDIUS")
Book.create(title: "TO THE LIGHTHOUSE")
Book.create(title: "AN AMERICAN TRAGEDY")
Book.create(title: "THE HEART IS A LONELY HUNTER")
Book.create(title: "SLAUGHTERHOUSE-FIVE")
Book.create(title: "INVISIBLE MAN")
Book.create(title: "NATIVE SON")
Book.create(title: "HENDERSON THE RAIN KING")
Book.create(title: "APPOINTMENT IN SAMARRA")
Book.create(title: "U.S.A.(trilogy)")
Book.create(title: "WINESBURG, OHIO")
Book.create(title: "A PASSAGE TO INDIA")
Book.create(title: "THE WINGS OF THE DOVE")
Book.create(title: "THE AMBASSADORS")
Book.create(title: "TENDER IS THE NIGHT")
Book.create(title: "THE STUDS LONIGAN TRILOGY")
Book.create(title: "THE GOOD SOLDIER")
Book.create(title: "ANIMAL FARM")
Book.create(title: "THE GOLDEN BOWL")
Book.create(title: "SISTER CARRIE")
Book.create(title: "A HANDFUL OF DUST")
Book.create(title: "AS I LAY DYING")
Book.create(title: "ALL THE KING’S MEN")
Book.create(title: "THE BRIDGE OF SAN LUIS REY")
Book.create(title: "HOWARDS END")
Book.create(title: "GO TELL IT ON THE MOUNTAIN")
Book.create(title: "THE HEART OF THE MATTER")
Book.create(title: "LORD OF THE FLIES")
Book.create(title: "DELIVERANCE")
Book.create(title: "A DANCE TO THE MUSIC OF TIME (series)")
Book.create(title: "POINT COUNTER POINT")
Book.create(title: "THE SUN ALSO RISES")
Book.create(title: "THE SECRET AGENT")
Book.create(title: "NOSTROMO")
Book.create(title: "THE RAINBOW")
Book.create(title: "WOMEN IN LOVE")
Book.create(title: "TROPIC OF CANCER")
Book.create(title: "THE NAKED AND THE DEAD")
Book.create(title: "PORTNOY’S COMPLAINT")
Book.create(title: "PALE FIRE")
Book.create(title: "LIGHT IN AUGUST")
Book.create(title: "ON THE ROAD")
Book.create(title: "THE MALTESE FALCON")
Book.create(title: "PARADE’S END")
Book.create(title: "THE AGE OF INNOCENCE")
Book.create(title: "ZULEIKA DOBSON")
Book.create(title: "THE MOVIEGOER")
Book.create(title: "DEATH COMES FOR THE ARCHBISHOP")
Book.create(title: "FROM HERE TO ETERNITY")
Book.create(title: "THE WAPSHOT CHRONICLES")
Book.create(title: "THE CATCHER IN THE RYE")
Book.create(title: "A CLOCKWORK ORANGE")
Book.create(title: "OF HUMAN BONDAGE")
Book.create(title: "HEART OF DARKNESS")
Book.create(title: "MAIN STREET")
Book.create(title: "THE HOUSE OF MIRTH")
Book.create(title: "THE ALEXANDRIA QUARTET")
Book.create(title: "A HIGH WIND IN JAMAICA")
Book.create(title: "A HOUSE FOR MR BISWAS")
Book.create(title: "THE DAY OF THE LOCUST")
Book.create(title: "A FAREWELL TO ARMS")
Book.create(title: "SCOOP")
Book.create(title: "THE PRIME OF MISS JEAN BRODIE")
Book.create(title: "FINNEGANS WAKE")
Book.create(title: "KIM")
Book.create(title: "A ROOM WITH A VIEW")
Book.create(title: "BRIDESHEAD REVISITED")
Book.create(title: "THE ADVENTURES OF AUGIE MARCH")
Book.create(title: "ANGLE OF REPOSE")
Book.create(title: "A BEND IN THE RIVER")
Book.create(title: "THE DEATH OF THE HEART")
Book.create(title: "LORD JIM")
Book.create(title: "RAGTIME")
Book.create(title: "THE OLD WIVES’ TALE")
Book.create(title: "THE CALL OF THE WILD")
Book.create(title: "LOVING")
Book.create(title: "MIDNIGHT’S CHILDREN")
Book.create(title: "TOBACCO ROAD")
Book.create(title: "IRONWEED")
Book.create(title: "THE MAGUS")
Book.create(title: "WIDE SARGASSO SEA")
Book.create(title: "UNDER THE NET")
Book.create(title: "SOPHIE’S CHOICE")
Book.create(title: "THE SHELTERING SKY")
Book.create(title: "THE POSTMAN ALWAYS RINGS TWICE")
Book.create(title: "THE GINGER MAN")
Book.create(title: "THE MAGNIFICENT AMBERSONS")
